begin;
update public.commerce_campaign set max_reservation_quantity=5,purchase_activated=false,reservations_open_at=null,purchase_open_at=null;
do $$
declare rid uuid; aid uuid; oid uuid; oid2 uuid; v public.product_variants; before_available integer; before_reserved integer; before_sold integer;
  a jsonb := '{"name":"Cliente SQL Test","line1":"Calle Pruebas 12","line2":"","postalCode":"28001","city":"Madrid","province":"28","country":"ES"}';
  customer jsonb := '{"name":"Cliente SQL Test","email":"sql-test@example.invalid","phone":"+34 600000000"}';
  req uuid := gen_random_uuid(); failed boolean := false;
begin
  select * into v from public.product_variants where sku='IE-CAMISETA-IMPERIAL-M';
  before_available:=v.available_stock;before_reserved:=v.reserved_stock;before_sold:=v.sold_stock;
  rid:=public.create_shirt_reservation(req,repeat('a',64),repeat('b',64),null,customer,a,'[{"sku":"IE-CAMISETA-IMPERIAL-M","quantity":5}]','2026-09-10','2026-09-10',0);
  if (select total_price_snapshot from public.reservations where id=rid) <> 14995 then raise exception 'WRONG_FINAL_PRICE'; end if;
  if (select available_stock from public.product_variants where id=v.id) <> before_available-5 then raise exception 'RESERVE_STOCK_FAILED'; end if;
  if public.create_shirt_reservation(req,repeat('a',64),repeat('b',64),null,customer,a,'[{"sku":"IE-CAMISETA-IMPERIAL-M","quantity":5}]','2026-09-10','2026-09-10',0) <> rid then raise exception 'IDEMPOTENCY_FAILED'; end if;
  begin perform public.create_shirt_reservation(req,repeat('c',64),repeat('b',64),null,customer,a,'[{"sku":"IE-CAMISETA-IMPERIAL-M","quantity":5}]','2026-09-10','2026-09-10',0); exception when others then failed:=true; end;
  if not failed then raise exception 'IDEMPOTENCY_CONFLICT_NOT_REJECTED'; end if;
  failed:=false;
  begin perform public.begin_shirt_payment(rid,a,'2026-09-10');exception when others then failed:=true;end;
  if not failed then raise exception 'UNOPENED_PURCHASE_ACCEPTED';end if;
  update public.commerce_campaign set purchase_activated=true;
  perform public.open_shirt_purchase(rid);
  update public.commerce_campaign set purchase_activated=false;
  aid:=public.begin_shirt_payment(rid,a,'2026-09-10');
  if public.begin_shirt_payment(rid,a,'2026-09-10') <> aid then raise exception 'CHECKOUT_IDEMPOTENCY_FAILED';end if;
  failed:=false;
  begin perform public.release_shirt_reservation(rid);exception when others then failed:=true;end;
  if not failed then raise exception 'CANCEL_DURING_PAYMENT_ACCEPTED';end if;
  failed:=false;
  begin perform public.complete_shirt_payment(aid,'cs_test_sql_fixture','pi_test_sql_fixture',1,'eur',2602,0);exception when others then failed:=true;end;
  if not failed then raise exception 'FORGED_TOTAL_ACCEPTED';end if;
  if exists(select 1 from public.commerce_orders where reservation_id=rid) then raise exception 'PARTIAL_ORDER_COMMITTED';end if;
  perform public.close_shirt_payment(aid,'cs_test_sql_fixture',false);
  if (select status from public.reservations where id=rid)<>'PAYMENT_FAILED' then raise exception 'FAILED_PAYMENT_STATE';end if;
  oid:=public.complete_shirt_payment(aid,'cs_test_sql_fixture','pi_test_sql_fixture',14995,'eur',2602,0);
  oid2:=public.complete_shirt_payment(aid,'cs_test_sql_fixture','pi_test_sql_fixture',14995,'eur',2602,0);
  if oid<>oid2 or (select count(*) from public.commerce_orders where reservation_id=rid)<>1 then raise exception 'DUPLICATE_ORDER';end if;
  if (select available_stock from public.product_variants where id=v.id) <> before_available-5 then raise exception 'DOUBLE_STOCK_DECREMENT';end if;
  if (select reserved_stock from public.product_variants where id=v.id) <> before_reserved or (select sold_stock from public.product_variants where id=v.id) <> before_sold+5 then raise exception 'STOCK_CONVERSION_FAILED';end if;
  if (select status from public.commerce_orders where id=oid) <> 'READY_FOR_FULFILLMENT' then raise exception 'ORDER_NOT_READY';end if;
  if (select shipping_address from public.commerce_orders where id=oid) <> a then raise exception 'ADDRESS_SNAPSHOT_FAILED';end if;
  update public.reservations set shipping_address=jsonb_set(a,'{line1}','"Otra direccion"') where id=rid;
  if (select shipping_address from public.commerce_orders where id=oid) <> a then raise exception 'ORDER_ADDRESS_MUTATED';end if;
  perform public.close_shirt_payment(aid,'cs_test_sql_fixture',true);
  if (select status from public.reservations where id=rid)<>'CONVERTED_TO_ORDER' then raise exception 'STALE_EVENT_REGRESSION';end if;
  perform public.update_commerce_fulfillment(oid,'PREPARING','','',null);
  perform public.update_commerce_fulfillment(oid,'READY_TO_SHIP','','',null);
  failed:=false;
  begin perform public.update_commerce_fulfillment(oid,'SHIPPED','','',null);exception when others then failed:=true;end;
  if not failed then raise exception 'SHIPPING_WITHOUT_TRACKING';end if;
  perform public.update_commerce_fulfillment(oid,'SHIPPED','Correos','TEST-NOT-A-REAL-SHIPMENT',null);
  perform public.update_commerce_fulfillment(oid,'DELIVERED','','',null);
  perform public.record_commerce_refund('pi_test_sql_fixture',14995);
  perform public.record_commerce_refund('pi_test_sql_fixture',14995);
  if (select status from public.commerce_orders where id=oid)<>'REFUNDED' then raise exception 'REFUND_FAILED';end if;
  if (select sold_stock from public.product_variants where id=v.id) <> before_sold+5 then raise exception 'REFUND_RESTOCKED_WITHOUT_RETURN';end if;
  if (select count(*) from public.commerce_outbox where reservation_id=rid and kind='ORDER_PAID')<>1 then raise exception 'DUPLICATE_EMAIL_JOB';end if;
  -- A mixed cart must roll back entirely when its second SKU cannot be reserved.
  before_available:=(select available_stock from public.product_variants where sku='IE-CAMISETA-IMPERIAL-L');
  failed:=false;
  begin perform public.create_shirt_reservation(gen_random_uuid(),repeat('a',64),repeat('b',64),null,customer,a,'[{"sku":"IE-CAMISETA-IMPERIAL-L","quantity":1},{"sku":"IE-CAMISETA-IMPERIAL-XXL","quantity":999}]','2026-09-10','2026-09-10',0);exception when others then failed:=true;end;
  if not failed or (select available_stock from public.product_variants where sku='IE-CAMISETA-IMPERIAL-L')<>before_available then raise exception 'PARTIAL_STOCK_COMMITTED';end if;
  rid:=public.create_shirt_reservation(gen_random_uuid(),repeat('a',64),repeat('b',64),null,customer,a,'[{"sku":"IE-CAMISETA-IMPERIAL-L","quantity":1}]','2026-09-10','2026-09-10',1);
  update public.reservations set expires_at=now()-interval '1 second' where id=rid;
  perform public.release_shirt_reservation(rid,'EXPIRED');
  perform public.release_shirt_reservation(rid,'EXPIRED');
  if (select available_stock from public.product_variants where sku='IE-CAMISETA-IMPERIAL-L')<>before_available then raise exception 'EXPIRATION_STOCK_FAILED';end if;
  perform public.claim_commerce_mail();
end $$;
select 'All transaction assertions passed; fixture payments and orders are rolled back.' as result;
rollback;
