import {useEffect,useState} from "preact/hooks";
type Stage={label:string;count:number;settled:number;lost:number;lossRate:number|null};
type Data={funnels:{flow:string;stages:Stage[];inProgress:number;largest:Stage|null}[];manifesto:{requests:number;accepted:number;failed:number;optIns:number;legacyRequests:number};checkout:Record<string,{opened:number;paid:number;expired:number;pending:number}>;paidOrders:number;clicks:{page:string;target:string;count:number}[]};
const names:Record<string,string>={manifesto:"Manifiesto",subscriptions:"Suscripciones",shirts:"Camisetas"};
export default function Funnel(){
  const [days,setDays]=useState(30),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const c=new AbortController();setData(null);setError("");fetch(`/api/admin/funnel?days=${days}`,{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error??"No se pudo cargar el embudo.");return d;}).then(setData).catch(e=>{if(e.name!=="AbortError")setError(e.message);});return()=>c.abort();},[days,refresh]);
  return <section><div class="admin-toolbar"><h1>Embudo</h1><label>Periodo<select value={days} onChange={e=>setDays(Number(e.currentTarget.value))}>{[7,30,90].map(n=><option key={n} value={n}>{n} dias</option>)}</select></label><button onClick={()=>setRefresh(n=>n+1)}>Actualizar</button></div>
    {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Cargando embudos...</p>}
    {data&&<><h2>Resultados reales</h2><div class="admin-metrics">{[["Solicitudes del manifiesto",data.manifesto.requests],["Envios aceptados del manifiesto",data.manifesto.accepted],["Fallos de envio del manifiesto",data.manifesto.failed],["Consentimientos newsletter",data.manifesto.optIns]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong></div>)}</div>
      {data.manifesto.legacyRequests>0&&<p>Solicitudes anteriores al nuevo registro: {data.manifesto.legacyRequests}. Su entrega no esta verificada en este registro.</p>}
      <div class="admin-table-wrap"><table><thead><tr><th>Stripe</th><th>Checkout creados</th><th>Pagados</th><th>Caducados sin pagar</th><th>Sin pago confirmado</th></tr></thead><tbody>{Object.entries(data.checkout).map(([flow,c])=><tr key={flow}><td>{names[flow]}</td><td>{c.opened}</td><td>{c.paid}</td><td>{c.expired}</td><td>{c.pending}</td></tr>)}</tbody></table></div>
      <p>Pedidos de camiseta confirmados: {data.paidOrders}. Los Checkout de prueba y los registros gratuitos no cuentan como ventas.</p>
      <h2>Recorridos con consentimiento de analitica</h2><p>Sesiones de navegador, no personas unicas. Sin avance significa 30 minutos sin actividad; las sesiones recientes siguen en curso. El ultimo paso mide la apertura de Stripe, no el pago. Los pagos de arriba son resultados independientes verificados con Stripe.</p>
      {data.funnels.map(f=><section class="admin-funnel" key={f.flow}><div class="admin-toolbar"><h2>{names[f.flow]}</h2><span>{f.inProgress} en curso</span></div><p class="admin-status">{f.largest?`Mayor perdida observada: ${f.largest.label} (${f.largest.lost} sesiones sin avance).`:"Sin perdidas observadas o muestra insuficiente."}</p>
        <div class="admin-table-wrap"><table><thead><tr><th>Etapa</th><th>Sesiones</th><th>Sin avance</th><th>Tasa sobre sesiones finalizadas</th></tr></thead><tbody>{f.stages.map((s,i)=><tr key={s.label}><td><span>{s.label}</span><meter aria-label={`Sesiones en ${s.label}`} min={0} max={Math.max(1,f.stages[0].count)} value={s.count}/></td><td>{s.count}</td><td>{i===f.stages.length-1?"No aplica":s.lost}</td><td>{s.lossRate===null||i===f.stages.length-1?"Sin muestra":`${(s.lossRate*100).toFixed(1)} %`}</td></tr>)}</tbody></table></div>
      </section>)}<h2>Clics mas frecuentes</h2><div class="admin-table-wrap"><table><thead><tr><th>Pagina</th><th>Elemento</th><th>Clics</th></tr></thead><tbody>{data.clicks.map(c=><tr key={`${c.page}:${c.target}`}><td>{c.page}</td><td>{c.target}</td><td>{c.count}</td></tr>)}{!data.clicks.length&&<tr><td colSpan={3}>Aun no hay clics consentidos en este periodo.</td></tr>}</tbody></table></div></>}
  </section>;
}
