export const SHIRT_FINAL_PRICE_CENTS = 2999;
export const TSHIRT_DISCOUNT_PERCENT = 15;
export const SHIRT_PRICE_COPY = "26,99 € de camiseta + 3 € de envío por unidad. IVA incluido. Solo Península";
export const RESERVATION_TERMS_VERSION = "2026-09-22";
export const RESERVATION_PURCHASE_NOTICE =
  "Te enviaremos por correo electr\u00f3nico el enlace de compra cuando se habilite la compra el 12 de octubre de 2026.";
export const formatMoney = (cents: number) =>
  new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(
    cents / 100,
  );
export const PROVINCES = [
  ["01", "Alava"],
  ["02", "Albacete"],
  ["03", "Alicante"],
  ["04", "Almeria"],
  ["05", "Avila"],
  ["06", "Badajoz"],
  ["08", "Barcelona"],
  ["09", "Burgos"],
  ["10", "Caceres"],
  ["11", "Cadiz"],
  ["12", "Castellon"],
  ["13", "Ciudad Real"],
  ["14", "Cordoba"],
  ["15", "A Coruna"],
  ["16", "Cuenca"],
  ["17", "Girona"],
  ["18", "Granada"],
  ["19", "Guadalajara"],
  ["20", "Gipuzkoa"],
  ["21", "Huelva"],
  ["22", "Huesca"],
  ["23", "Jaen"],
  ["24", "Leon"],
  ["25", "Lleida"],
  ["26", "La Rioja"],
  ["27", "Lugo"],
  ["28", "Madrid"],
  ["29", "Malaga"],
  ["30", "Murcia"],
  ["31", "Navarra"],
  ["32", "Ourense"],
  ["33", "Asturias"],
  ["34", "Palencia"],
  ["36", "Pontevedra"],
  ["37", "Salamanca"],
  ["39", "Cantabria"],
  ["40", "Segovia"],
  ["41", "Sevilla"],
  ["42", "Soria"],
  ["43", "Tarragona"],
  ["44", "Teruel"],
  ["45", "Toledo"],
  ["46", "Valencia"],
  ["47", "Valladolid"],
  ["48", "Bizkaia"],
  ["49", "Zamora"],
  ["50", "Zaragoza"],
] as const;
export const RESERVATION_STATUS: Record<string, string> = {
  WAITLIST: "Lista de espera",
  RESERVED: "Reservada",
  PURCHASE_AVAILABLE: "Compra disponible",
  PAYMENT_PENDING: "Pago pendiente",
  PAYMENT_FAILED: "Pago no completado",
  PAID: "Pagada",
  CONVERTED_TO_ORDER: "Pedido confirmado",
  CANCELLED: "Cancelada",
  EXPIRED: "Caducada",
  READY_FOR_FULFILLMENT: "Lista para preparar",
  PREPARING: "En preparacion",
  READY_TO_SHIP: "Lista para enviar",
  SHIPPED: "Enviada",
  DELIVERED: "Entregada",
  REFUNDED: "Reembolsada",
};
